application: migovec-survey
version: 7
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
 
#- url: /survey
#  static_dir: survey

- url: /.*
  script: migovec-survey.app
  
- url: /favicon\.ico
  static_files: static/icons/favicon.ico
  upload: static/icons/favicon\.ico
  
libraries:
- name: jinja2
  version: latest
  